### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by xerosanyam** [vramework/schemats#14]
the library is not working anymore.
`schemats postgres -c postgresql://user@localhost:5432/postgres -t logs -o logs.ts`

**Comment by raultruco** [comment]
> the library is not working anymore. `schemats postgres -c postgresql://user@localhost:5432/postgres -t logs -o logs.ts`

The parameters has changed slightly in this version (ie: the connection is now an argument, not an option):

`schemats postgres -s public  -t logs -o logs.ts -C 
 postgresql://user:password@localhost:5432/postgres`

**Comment by yasserf** [comment]
@raultruco it was never an option

the -c means camel case

I think the issue with @xerosanyam is that he put the argument in the middle of the options instead of the end

closing this as it is just invalid use of cli commands (please let me know if it isn't!)
