### ISSUE TITLE
postgis types

### ISSUE THREAD

**Issue by Kim-Andersen** [vramework/schemats#15]
Hi,
First of all; great lib. It's super useful.

Not unlike many people I suppose, I'm using Postgis for geo-based stuff and it seems the Postgis types are not supported, like `geography(Point,4326)` , which is a game-stopper, unfortunately

Do you plan to add support for these types, maybe beginning with the most popular ones?
Or is there a way to map unknown types to whatever TS type you like?

Thanks in advance.

**Comment by Kim-Andersen** [comment]
By plugin, do you mean that your tool supports plugins?

**Comment by yasserf** [comment]
yup, sorry I guess correct word might be postgres extension.

**Comment by Kim-Andersen** [comment]
It seems the postgis types appear in the `pg_type` table, at the `geography` type I'm looking for.

Would you take a PR for this type only? Then maybe I'll PR in more types as I get the hang of it.

**Comment by Kim-Andersen** [comment]
I just discovered the `--no-throw-on-missing-type` flag by accident. So I can do some TS magic to cast the `unknown` type to what I need it to be. So all good.

**Comment by yasserf** [comment]
i would be happy to add a PR for that if it stops you from needing to do TS magic, but up to you!

**Comment by Kim-Andersen** [comment]
The thing is that Postgis has both `geometry` and `geography` types, each with different sub types (`linestring`, `point` etc), and you to call certain Postgres functions to extract ie. lat and lng from those types. So it's not a trivial conversion to a Typescript type. So I'm not sure how to handle this in a generic way, though it would be very neat.

http://postgis.net/workshops/postgis-intro/geography.html
http://postgis.net/workshops/postgis-intro/geometries.html
