### ISSUE TITLE
Add option to disable bigint.

### ISSUE THREAD

**Issue by wirekang** [vramework/schemats#17]

**Comment by yasserf** [comment]
Can you please provide a bit more information on this issue?

**Comment by wirekang** [comment]
Sorry for the lack of information. If there is a `bigint` (=sql type) column, `schemats` will create a `bigint` (=js type) attribute. Although this is very appropriate behavior, and JavaScript numbers don't cover the range of all possible 64-bit integer values, sometimes we need 'number' rather than 'bigint'. It would be nice to have an option like `--no-bigint`.
